services:
  trip-postgres:
    image: postgres:15
    container_name: trip-postgres
    restart: always
    environment:
      POSTGRES_DB: llt-trip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trip_service_password_123
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - llt-net
    ports:
      - '5433:5432'

  trip-service:
    container_name: trip-service
    restart: always
    ports:
      - '3002:3002'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - trip-postgres
    networks:
      - llt-net

networks:
  llt-net:
    external: true
    name: llt-net
