services:
  trip-service:
    container_name: trip-service
    restart: always
    ports:
      - 3002:3002
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - llt-net

networks:
  llt-net:
    external: true
    name: llt-net
